### ISSUE TITLE
How to fix this error when installing `audic`

### ISSUE THREAD

**Issue by kennarddh** [Richienb/vlc-static#7]
```
npm ERR! code 1
npm ERR! path D:\SomePath\node_modules\vlc-static
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install
npm ERR! D:\SomePath\node_modules\download\node_modules\got\index.js:182
npm ERR!                                ee.emit('error', new got.RequestError(err, opts));
npm ERR!                                                 ^
npm ERR!
npm ERR! GotError [RequestError]: connect ETIMEDOUT 0000:000:0:3:0000:0000:0000:0:443
npm ERR!     at ClientRequest.<anonymous> (D:\SomePath\node_modules\download\node_modules\got\index.js:182:22)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:494:9)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   host: 'download.videolan.org',
npm ERR!   hostname: 'download.videolan.org',
npm ERR!   method: 'GET',
npm ERR!   path: '/pub/videolan/vlc/3.0.16/win64/vlc-3.0.16-win64.zip',
npm ERR!   protocol: 'https:',
npm ERR!   url: 'https://download.videolan.org/pub/videolan/vlc/3.0.16/win64/vlc-3.0.16-win64.zip'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-\AppData\Local\npm-cache\_logs\2023-06-12T08_57_57_631Z-debug-0.log
```

## Environment
- NodeJS: v18.12.1
- NPM: 9.5.0
- Audic: 3.0.2
- OS: Windows 10

After I added `C:\Program Files (x86)\VideoLAN\VLC\` to user path and restart `VSCode` it still throw error.

**Comment by jorisvilardell** [comment]
```
 Progress: resolved 871, reused 0, downloaded 862, added 862, done
.../node_modules/@swc/core postinstall$ node postinstall.js
.../node_modules/vlc-static install$ node install
.../node_modules/@swc/core postinstall: Done
.../node_modules/vlc-static install: /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10
.../node_modules/vlc-static install:   Object.assign(new Error(`not found: ${cmd}`), { code: 'ENOENT' })
.../node_modules/vlc-static install:                 ^
.../node_modules/vlc-static install: Error: not found: vlc
.../node_modules/vlc-static install:     at getNotFoundError (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10:17)
.../node_modules/vlc-static install:     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:57:18
.../node_modules/vlc-static install:     at new Promise (<anonymous>)
.../node_modules/vlc-static install:     at step (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:54:21)
.../node_modules/vlc-static install:     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:71:22
.../node_modules/vlc-static install:     at new Promise (<anonymous>)
.../node_modules/vlc-static install:     at subStep (/home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:69:33)
.../node_modules/vlc-static install:     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:80:22
.../node_modules/vlc-static install:     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/index.js:42:5
.../node_modules/vlc-static install:     at /home/runner/work/E2Q/E2Q/e2q-back/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/mode.js:8:5 {
.../node_modules/vlc-static install:   code: 'ENOENT'
.../node_modules/vlc-static install: }
.../node_modules/vlc-static install: Node.js v20.17.0
.../node_modules/vlc-static install: Failed
 ELIFECYCLE  Command failed with exit code 1.
 
```
 
 Same things with my CI I can't use Audic. Please fix it !
 
 My CI:
 
```yaml
 name: Run Adonis Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2q-back/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: e2q
          POSTGRES_PASSWORD: e2q-test-runner
          POSTGRES_DB: E2Q-Test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run tests
        run: pnpm run refreshdb && npm run test
        env:
          TZ: UTC
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: info
          APP_KEY: TestingEnvironnement-E2QRunnerTe
          NODE_ENV: test

          DB_HOST: postgres
          DB_CONNECTION: postgres
          DB_PORT: 5432
          DB_USER: e2q
          DB_PASSWORD: e2q-test-runner
          DB_DATABASE: E2Q-Test

          ADMIN_USER: admin-test
          ADMIN_IDENTIFIANT: admin-test
```
